name: Schedule automation
on: 
  schedule:
    - cron: '0 11 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          ls
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI pandas numpy matplotlib mplfinance
      - name: Run
        run: |
          python3 ./b3-checker/main.py
